\documentclass[final,los,noindex,glossary,noloa,10pt]{mythesis}

\usepackage{array,booktabs,nameref,bbding,enumitem,epigraph,tabularx,longtable,lscape,tikz,pifont,amsmath,amsfonts,listings,float,framed,dcolumn,footnote,multirow, amsthm}
\usepackage[noline, linesnumbered]{algorithm2e}
\usepackage[figuresright]{rotating}
\usepackage[update,prepend]{epstopdf}
\usepackage[font=scriptsize]{subcaption}
\usepackage{upgreek}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
%\usepackage{subscript} % provides \textsubscript

\usepackage{fancyvrb}
\VerbatimFootnotes % allows verbatim text in footnotes
\fvset{fontsize=\scriptsize}

\usetikzlibrary{calc,intersections,through,backgrounds,matrix,mindmap}
\usepackage{tikz-3dplot}

\numberwithin{equation}{section} % amsmath - numbering scheme two deep for equations
\setcounter{tocdepth}{2}

% Options for 'framed'
\setlength\FrameSep{0.5cm}
\setlength\FrameRule{0.1pt}
\setlength{\epigraphrule}{0pt}
\setlength\extrarowheight{3pt}

% Options for algorithm2e
\SetAlCapSkip{2em}
\SetKwProg{Def}{Function}{:}{}
\SetKwBlock{Prob}{with probability }{end}
\DontPrintSemicolon

% Options for amsthm
\newtheorem{hypothesis}{Hypothesis}[chapter]

\author{Thom Young}
\title{The Emergence of\\Evolution in\\Artificial Systems}
\degree{A thesis submitted in partial fulfilment of the requirements for the degree of Doctor of Philosophy in Computer
Science in the University of Canterbury}
\abstract{
	This work is motivated by the vision of achieving a self-improving, self-organizing, system.
	There are a number of possible ways in which this might be achieved, but other than in very specific domains, it remains an open problem.
	
	One approach is inspired by Biology, and natural evolution.
	Foundation for several related bodies of literature, in Evolutionary Algorithms, Optimizers, and Evolutionary Computing, as well of course of the study of evolution
	in natural systems.
	As many have observed, there are major differences between the original inspiration and the spin-offs. Biological evolutionary systems are complex, contingent, emergent, endogenous and general. As applied to technology, evolutionary systems are exogenous, problem-specific and designed.
	
	A convenient shorthand capturing these differences labels the biological original as bottom-up and the derived fields as top-down.
	If the top-down approach has failed, then perhaps there might be mileage in returning to biology, our sole example of a general self-improving, self-organizing system.
	
	But as biology is contingent, what is the most useful starting point for a recapitulation? 
	Assume first of all that we are in the domain of software, rather than hardware or wetware, for practical reasons.
	Assume also then that biological evolution does not depend upon embodiment - that the outcome can be adequately modelled at a conceptual level without being grounded in either the physical world, or in contingent biology such as enzymes, proteins and genes.
	
	Our goal then is to determine the (or perhaps a) most parsimonious starting point that allows conceptual (not historical) biological evolution to begin.
	Evolution generally thought to require three components - variation, selection and inheritance. Inheritance refers to the correlation between parent and child traits. Previous work has shown that inheritance, instead of being a prerequisite for evolution, is in fact a product of evolution under some conditions, emerging from the interaction of variation and selection.
	
	We strengthen the characterization of the conditions under which inheritance emerges by a systematic series of experiments.
	We also extend the earlier result from a fixed relationship between entities and the environment to one in which the environment, and hence the relationship, changes. Changing environments in other fields bring benefits to robustness and to the overall quality of the solution.
	Next we describe how a plausible mechanism based on an evolutionary copy-operator can meet the conditions for inheritance in a practical system.
	Finally, we take the first steps towards the implementation of the mechanism in an Artificial Chemistry.
}
\acknowledgements{Dedicated to my family, and to all those who helped me.}

\usereferences
\addtoreferences{mythesis}
\biblatexstyle{authoryear}

\begin{document}
\listofalgorithms
\include{glossary}
\include{body}
\part{Appendices}
\appendix{
\include{appendices}
}
\end{document}
